### ISSUE TITLE
script titles shouldn't change color

### ISSUE THREAD

**Issue by Jaizu** [SBird1337/poryscript-language#17]
I'm not very good at explaining myself but there, grab a screenshot 
![image](https://user-images.githubusercontent.com/18596778/124359625-125ec200-dc26-11eb-91a2-58e00df52712.png)

It also happens in the movement and text ones.

**Comment by Jaizu** [comment]
Addtionally comments are also bugged! 
![image](https://user-images.githubusercontent.com/18596778/124382915-180de380-dcca-11eb-8043-569281e8c2ee.png)
![image](https://user-images.githubusercontent.com/18596778/124382923-222fe200-dcca-11eb-9f1c-6e3dcc485362.png)

**Comment by SBird1337** [comment]
This looks to be a general problem with the semantic highlighting which currently overrides everything it finds...

**Comment by SBird1337** [comment]
fixed in 2.1.0 (a8375499660c08863e977d31b29e015671d1a98c)
