### ISSUE TITLE
Extension constantly throwing errors in VSCode

### ISSUE THREAD

**Issue by LucaBGt** [SBird1337/poryscript-language#18]
Hi!
Sorry if this is the incorrect place to ask about the VSCode extension, but I have this issue:

When the extension is downloading, turning it on spams these error messages in the output which makes it almost impossible to do anything:
> 
> (node:53711) UnhandledPromiseRejectionWarning: Error: Request poryscript/getPoryscriptFiles failed with message: Cannot read property '0' of undefined
>     at handleResponse (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
>     at processMessageQueue (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
>     at Immediate.<anonymous> (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
>     at processImmediate (internal/timers.js:461:21)
> (Use `Code Helper (Renderer) --trace-warnings ...` to show where the warning was created)
> (node:53711) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:53711) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> (node:53711) UnhandledPromiseRejectionWarning: Error: Request poryscript/readfile failed with message: Cannot read property '0' of undefined
>     at handleResponse (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
>     at processMessageQueue (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
>     at Immediate.<anonymous> (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
>     at processImmediate (internal/timers.js:461:21)
> (node:53711) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> (node:53711) UnhandledPromiseRejectionWarning: Error: Request poryscript/readfile failed with message: Cannot read property '0' of undefined
>     at handleResponse (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
>     at processMessageQueue (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
>     at Immediate.<anonymous> (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
>     at processImmediate (internal/timers.js:461:21)
> (node:53711) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
> (node:53711) UnhandledPromiseRejectionWarning: Error: Request poryscript/readfile failed with message: Cannot read property '0' of undefined
>     at handleResponse (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
>     at processMessageQueue (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
>     at Immediate.<anonymous> (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
>     at processImmediate (internal/timers.js:461:21)
> (node:53711) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
> (node:53711) UnhandledPromiseRejectionWarning: Error: Request poryscript/readfile failed with message: Cannot read property '0' of undefined
>     at handleResponse (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
>     at processMessageQueue (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
>     at Immediate.<anonymous> (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
>     at processImmediate (internal/timers.js:461:21)
> (node:53711) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
> (node:53711) UnhandledPromiseRejectionWarning: Error: Request poryscript/readfile failed with message: Cannot read property '0' of undefined
>     at handleResponse (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
>     at processMessageQueue (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
>     at Immediate.<anonymous> (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
>     at processImmediate (internal/timers.js:461:21)
> (node:53711) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
> (node:53711) UnhandledPromiseRejectionWarning: Error: Request poryscript/readfile failed with message: Cannot read property '0' of undefined
>     at handleResponse (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
>     at processMessageQueue (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
>     at Immediate.<anonymous> (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
>     at processImmediate (internal/timers.js:461:21)
> (node:53711) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
> (node:53711) UnhandledPromiseRejectionWarning: Error: Request poryscript/readfile failed with message: Cannot read property '0' of undefined
>     at handleResponse (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
>     at processMessageQueue (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
>     at Immediate.<anonymous> (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
>     at processImmediate (internal/timers.js:461:21)
> (node:53711) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
> (node:53711) UnhandledPromiseRejectionWarning: Error: Request poryscript/readfile failed with message: Cannot read property '0' of undefined
>     at handleResponse (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
>     at processMessageQueue (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
>     at Immediate.<anonymous> (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
>     at processImmediate (internal/timers.js:461:21)
> (node:53711) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
> (node:53711) UnhandledPromiseRejectionWarning: Error: Request poryscript/readfile failed with message: Cannot read property '0' of undefined
>     at handleResponse (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
>     at processMessageQueue (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
>     at Immediate.<anonymous> (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
>     at processImmediate (internal/timers.js:461:21)
> (node:53711) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
> [Error - 9:50:56 PM] Request textDocument/semanticTokens/full failed.
>   Message: Request poryscript/readfile failed with message: Cannot read property '0' of undefined
>   Code: -32603 
> (node:53711) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 4)
> (node:53711) UnhandledPromiseRejectionWarning: Error: Request poryscript/readfile failed with message: Cannot read property '0' of undefined
>     at handleResponse (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
>     at processMessageQueue (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
>     at Immediate.<anonymous> (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
>     at processImmediate (internal/timers.js:461:21)
> (node:53711) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)
> (node:53711) UnhandledPromiseRejectionWarning: Error: Request poryscript/readfile failed with message: Cannot read property '0' of undefined
>     at handleResponse (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
>     at processMessageQueue (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
>     at Immediate.<anonymous> (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
>     at processImmediate (internal/timers.js:461:21)
> (node:53711) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
> (node:53711) UnhandledPromiseRejectionWarning: Error: Request poryscript/readfile failed with message: Cannot read property '0' of undefined
>     at handleResponse (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
>     at processMessageQueue (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
>     at Immediate.<anonymous> (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
>     at processImmediate (internal/timers.js:461:21)
> (node:53711) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 13)
> (node:53711) UnhandledPromiseRejectionWarning: Error: Request poryscript/readfile failed with message: Cannot read property '0' of undefined
>     at handleResponse (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
>     at processMessageQueue (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
>     at Immediate.<anonymous> (/Users/lucabaumgart/.vscode/extensions/karathan.poryscript-2.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
>     at processImmediate (internal/timers.js:461:21)
> (node:53711) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
> 
etc. etc. etc.

Saving will show these errors:

> [Error - 9:54:33 PM] Request textDocument/semanticTokens/range failed.
  Message: Request poryscript/readfile failed with message: Cannot read property '0' of undefined
  Code: -32603 
[Error - 9:54:34 PM] Request textDocument/definition failed.
  Message: Request poryscript/readfile failed with message: Cannot read property '0' of undefined
  Code: -32603 
[Error - 9:54:35 PM] Request textDocument/definition failed.
  Message: Request poryscript/readfile failed with message: Cannot read property '0' of undefined
  Code: -32603 

Any help would be great, thanks!

**Comment by SBird1337** [comment]
Hi, I think you are using the extension with only a single file open. The extension is the nunable to read files in a non-existant workspace. Make sure to open the whole workspace ("Folder") in VSCode.

Regardless the extension should handle errors and not blindly spam messages, so I will address this in a future release. (Still, to be functional it needs your workspace information to gather information about e.g. script commands)

**Comment by xBsWYA2wYfuxW0FB** [comment]
I've got the same issue, but I actually opened the workspace as a folder in Windows 10 (not WSL), as VSCode now allows to launch a WSL console without having to open the folder remotely.

**Comment by vexio** [comment]
Glad to know I'm not the only one getting spammed with these errors. I also have my VSCode setup so the entire folder for my decomp is open, but I still get spammed with these errors.

**Comment by SBird1337** [comment]
should be fixed by #20
