### ISSUE TITLE
Missing # for single-line comments

### ISSUE THREAD

**Issue by huderlem** [SBird1337/poryscript-language#3]
Both `//` and `#` are valid line comments in Poryscript, but only `//` is specified in the language config.

**Comment by huderlem** [comment]
Looking closer at this, it seems they are indeed both specified already.  The setting in `language-configuration.json` just control which character it uses when you use keyboard shortcuts to comment.

**Comment by SBird1337** [comment]
Exactly, this only affects what the editor appends when issuing Multiline Comment/Uncomment (`Ctrl+/`)
