### ISSUE TITLE
Add syntax highlighting for the labels

### ISSUE THREAD

**Issue by huderlem** [SBird1337/poryscript-language#5]
The labels for scripts, texts, etc. could use some color.  Right now, they aren't recognized as special tokens.

**Comment by SBird1337** [comment]
How would it know that something is a label? Currently this is not aware of the semantics of the language, and syntax highlighting is based on Regular Expressions. Also, do you mean the definition of a label, as in

```
script Script_ThisShouldBeHighlighted {}
```
or inside of command arguments, as in
```
msgbox(thisTextLabelShouldBeHighlighted)
```
The latter cannot even semantically be distinguished until everything was preprocessed.

**Comment by huderlem** [comment]
>How would it know that something is a label?
I guess it would be the symbol occurring after the top-level commands?  I don't know anything about VS Code extensions, though.

**Comment by SBird1337** [comment]
ed7b251ede44c47b4708b89e22f0de1f230b9444
